name: VirusTotal Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Scan files with VirusTotal
      env:
        VT_API_KEY: ${{ secrets.VT_API_KEY }}
      run: |
        for file in $(find . -type f); do
          echo "Scanning $file"
          curl -s \
            --request POST \
            --url https://www.virustotal.com/api/v3/files \
            --header "x-apikey: $VT_API_KEY" \
            --form "file=@$file"
          sleep 20
        done
